# Generated by Django 2.1.2 on 2018-10-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('imdb_id', models.CharField(max_length=32)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('canceled', models.BooleanField()),
            ],
        ),
    ]
