# Generated by Django 2.1.2 on 2018-10-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20181016_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='entry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Entry'),
        ),
    ]
